Add ophys devices from ndx-ophys-devices
catalystneuro/ndx-microscopy pull request #22
Opened 2024-08-26 15:43 UTC by alessandratrapani

## Entity relationship diagram

```mermaid
%%{init: {'theme': 'base', 'themeVariables': {'primaryColor': '#ffffff', "primaryBorderColor': '#144E73', 'lineColor': '#D96F32'}}}%%

classDiagram
    direction BT

    class MicroscopySeries {
        <<TimeSeries>>

        --------------------------------------
        links
        --------------------------------------
        microscope : Microscope
        excitation_light_path : ExcitationLightPath
        emission_light_path : EmissionLightPath
    }

    class PlanarMicroscopySeries {
        <<MicroscopySeries>>

        --------------------------------------
        datasets
        --------------------------------------
        data : numeric, frame x height x width
        --> unit : text

        --------------------------------------
        links
        --------------------------------------
        imaging_space : PlanarImagingSpace
    }

    class VariableDepthMicroscopySeries {
        <<MicroscopySeries>>

        --------------------------------------
        datasets
        --------------------------------------
        data : numeric, frame x height x width
        --> unit : text
        depth_per_frame_in_um : numeric, length of frames

        --------------------------------------
        links
        --------------------------------------
        imaging_space : PlanarImagingSpace
    }

    class VolumetricMicroscopySeries {
        <<MicroscopySeries>>

        --------------------------------------
        datasets
        --------------------------------------
        data : numeric, frame x height x width x depth
        --> unit : text

        --------------------------------------
        links
        --------------------------------------
        imaging_space : VolumetricImageSpace
    }

    class MultiChannelMicroscopyVolume {
        <<NWBDataInterface>>
        
        --------------------------------------
        attributes
        --------------------------------------
        description : text, optional
        unit : text, optional
        conversion : numeric, optional
        offset : numeric, optional

        --------------------------------------
        datasets
        --------------------------------------
        data : numeric, frame x height x width x depth x emission_light_paths
        --> unit : text
        excitation_light_paths : ExcitationLightPath, excitation_light_paths
        emission_light_paths : EmissionLightPath, emission_light_paths
        
        --------------------------------------
        links
        --------------------------------------
        imaging_space : VolumetricImageSpace
        microscope : Microscope
    }
    
    class ImagingSpace{
        <<NWBContainer>>

        --------------------------------------
        datasets
        --------------------------------------
        description : text
        origin_coordinates : numeric, length 3, optional
        --> unit : text, default="micrometers"

        --------------------------------------
        attributes
        --------------------------------------
        location : text, optional
    }

    class PlanarImagingSpace{
        <<ImagingSpace>>

        --------------------------------------
        datasets
        --------------------------------------
        grid_spacing : numeric, length 2, optional
        --> unit : text, default="micrometers"

        --------------------------------------
        attributes
        --------------------------------------
        reference_frame : text, optional
    }

    class VolumetricImagingSpace{
        <<ImagingSpace>>

        --------------------------------------
        datasets
        --------------------------------------
        grid_spacing : numeric, length 2, optional
        --> unit : text, default="micrometers"

        --------------------------------------
        attributes
        --------------------------------------
        reference_frame : text, optional
    }

    class ExcitationLightPath{
        <<NWBContainer>>

        --------------------------------------
        links
        --------------------------------------
        excitation_source : ExcitationSource, optional
        excitation_filter : OpticalFilter, optional

        --------------------------------------
        attributes
        --------------------------------------
        excitation_wavelength_in_nm : numeric
    }

    class EmissionLightPath{
        <<NWBContainer>>

        --------------------------------------
        links
        --------------------------------------
        photodetector : Photodetector, optional
        emission_filter : OpticalFilter, optional

        --------------------------------------
        attributes
        --------------------------------------
        emission_wavelength_in_nm : numeric
    }

    class Microscope{
        <<Device>>

        --------------------------------------
        attributes
        --------------------------------------
        model : text, optional
    }

    PlanarMicroscopySeries *-- MicroscopySeries : extends
    PlanarMicroscopySeries -- PlanarImagingSpace : links
    VariableDepthMicroscopySeries *-- MicroscopySeries : extends
    VariableDepthMicroscopySeries -- PlanarImagingSpace : links
    VolumetricMicroscopySeries *-- MicroscopySeries : extends
    VolumetricMicroscopySeries -- VolumetricImagingSpace : links
    MultiChannelMicroscopyVolume *-- MicroscopySeries : extends
    MultiChannelMicroscopyVolume -- VolumetricImagingSpace : links
    PlanarImagingSpace *-- ImagingSpace : extends
    VolumetricImagingSpace *-- ImagingSpace : extends
    MicroscopySeries ..> Microscope : links
    MicroscopySeries ..> ExcitationLightPath : links
    MicroscopySeries ..> EmissionLightPath : links
```

2025-01-16 10:31 UTC, alessandratrapani commented
@pauladkisson Sorry for the messy PR. I'll try to explain what I did here:

1. Added neurodata types from ndx-ophys-devices
2. Update tests
3. Update the entity relationship diagram in the README

Basically, I am asking you to review the following files that contain those 3 changes:

- README.md
- requirements-dev.txt
- requirements-min.txt
- spec/ndx-microscopy.extensions.yaml
- spec/ndx-microscopy.namespace.yaml
- src/pynwb/ndx_microscopy/__init__.py
- src/pynwb/ndx_microscopy/testing/__init__.py
- src/pynwb/ndx_microscopy/testing/_mock.py
- src/pynwb/tests/test_constructors.py
- src/pynwb/tests/test_roundtrip.py

All the other files have already been reviewed in #26, where we updated the base template for the extension and fixed the import of ndx-ophys-device (#23).

2025-01-16 23:08 UTC, pauladkisson requested changes
Overall looks good! I made a few suggestions but nothing major.

I think it would help me a lot to have a quick meeting on this to make sure I understand what's going on (esp. with the newer types). I marked some questions _ZoomQ_ for that purpose.

2025-01-16 23:08 UTC, pauladkisson commented on src/pynwb/tests/test_roundtrip.py
>          nwbfile.add_acquisition(nwbdata=planar_microscopy_series)
What happens if you add a PlanarMicroscopySeries to acquisition, but forget to add one of its devices?

I ask bc I've made this mistake and sometimes it fails ungracefully (ex. write works but read fails).

2025-01-16 23:57 UTC, rly commented on requirements-min.txt
> +pynwb==2.8.0
@pauladkisson I *think* you may be confused with the purpose of this file, and I admit this file from the ndx-template is confusing. This is used *only* in GitHub Actions to check that tests pass when these lower bounds of versions of dependencies are used. The version ranges of dependencies allowed is specified in `pyproject.toml` and uses `>=`:
```
    "pynwb>=2.8.0",
    "hdmf>=3.14.1",
```
I recommend setting and testing minimum versions of dependencies because pynwb and hdmf have changed over time and this extension may not work with, e.g., hdmf 3.8.

2025-01-17 17:28 UTC, pauladkisson commented on requirements-min.txt
> +pynwb==2.8.0
Ah, I see. My bad, thanks for the correction.

2025-01-23 13:55 UTC, alessandratrapani commented on spec/ndx-microscopy.extensions.yaml
>    - neurodata_type_def: ImagingSpace
yes

2025-01-23 13:59 UTC, alessandratrapani commented on spec/ndx-microscopy.extensions.yaml
> +        quantity: '?'
Inluded in both Emission and Excitation light path

2025-01-23 14:32 UTC, alessandratrapani commented on src/pynwb/tests/test_roundtrip.py
>          nwbfile.add_acquisition(nwbdata=planar_microscopy_series)
This is the error you would get: 
```bash
hdmf.build.errors.OrphanContainerBuildError: PlanarMicroscopySeries (PlanarMicroscopySeries): Linked Microscope 'Microscope' has no parent. Remove the link or ensure the linked container is added properly.
```

Adding a failing test

2025-01-23 15:08 UTC, alessandratrapani commented
In a follow-up PR I will:

- [ ] add a check for the `excitation_wavelength_in_nm ` and  `emission_wavelength_in_nm` defined in respectively in ExcitationSource and ExcitationLightPath and in Photodetector and EmissionLightPath (and add tests)

- [ ] make ExcitationLightPath, EmissionLightPath and ImagingSpase NWBContainer not LabMetaData

2025-01-23 18:27 UTC, pauladkisson commented on src/pynwb/tests/test_roundtrip.py
>          nwbfile.add_acquisition(nwbdata=planar_microscopy_series)
Thanks for checking! Just to clarify, this error occurs during `io.write(nwbfile)` correct?

2025-01-23 18:37 UTC, pauladkisson approved these changes
LGTM!

2025-01-24 07:48 UTC, merged